routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;

// user management
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\PermissionController;

// authentication
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\ForgotPasswordController;
use App\Http\Controllers\ProfileController;

// data env
use App\Http\Controllers\MenuController;

// data master
use App\Http\Controllers\AdjustmentTypeController;
use App\Http\Controllers\BusinessInformationController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\CashAndBankController;
use App\Http\Controllers\CashAndBankSubcategoryController;
use App\Http\Controllers\ChartOfAccountController;
use App\Http\Controllers\CommodityCategoryController;
use App\Http\Controllers\CurrencyController;
use App\Http\Controllers\CostTypeOtherController;
use App\Http\Controllers\SpecialNotificationBarController;
use App\Http\Controllers\FormStyleController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\InventoryTypeController;
use App\Http\Controllers\ProductCategoryController;
use App\Http\Controllers\ProductionCostsTypeController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\DiscountTypeController;
use App\Http\Controllers\TaxTypesController;
use App\Http\Controllers\AssetCategoryController;
use App\Http\Controllers\BannersTutorialController;
use App\Http\Controllers\PromotionalBannersController;
use App\Http\Controllers\TaxesController;
use App\Http\Controllers\SolutionListController;
use App\Http\Controllers\AssetsController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\UnitsController;
use App\Http\Controllers\SampleTransactionController;
use App\Http\Controllers\CompanyCustomerController;
use App\Http\Controllers\ShopController;


use App\Http\Controllers\CommoditySecurityController;
use App\Http\Controllers\CompanyCategoryController;
use App\Http\Controllers\CompanyRoleController;
use App\Http\Controllers\MarketingChannelController;
use App\Http\Controllers\NumberOfEmployeeController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\TransactionTagController;



// transaction
use App\Http\Controllers\TransactionController;
use App\Http\Requests\SolutionListRequest;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
// Authentications
Route::get('/login', [AuthController::class, 'loginForm'])->name('login');
Route::post('/login-submit', [AuthController::class, 'login'])->name('login.submit');
Route::get('/register', [AuthController::class, 'registerForm'])->name('register-form');
Route::post('/register/verify-email', [AuthController::class, 'registerVerifyEmail'])->name('register.verify-email');
Route::post('/register/get-otp', [AuthController::class, 'registerGetOtp'])->name('register.get-otp');
Route::post('/register/verify-otp', [AuthController::class, 'registerVerifyOtp'])->name('register.verify-otp');
Route::post('/register/user', [AuthController::class, 'registerUser'])->name('register.user');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout.user');

// forgot password
Route::get('forget-password', [ForgotPasswordController::class, 'showForgetPasswordForm'])->name('forget.password.get');
Route::post('forget-password', [ForgotPasswordController::class, 'submitForgetPasswordForm'])->name('forget.password.post');
Route::get('reset-password-status/{status}', [ForgotPasswordController::class, 'resetPasswordStatus'])->name('reset.password.status');
Route::get('reset-password/{token}', [ForgotPasswordController::class, 'showResetPasswordForm'])->name('reset.password.get');
Route::post('reset-password/{token}', [ForgotPasswordController::class, 'submitResetPasswordForm'])->name('reset.password.post');

Route::middleware(['auth'])->group(function () {
    Route::get('/register/complete', [AuthController::class, 'registerComplete'])->name('register.complete');
    Route::post('/register', [AuthController::class, 'register'])->name('register');

    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('user', UserController::class)->except(['update']);
    Route::post('user/{id}', [UserController::class, 'update'])->name('user.update');
    Route::post('roles/{role}', [RoleController::class, 'update'])->name('admin.roles.update');
    Route::resource('roles', RoleController::class);
    Route::resource('permissions', PermissionController::class);

    // data env
    Route::resource('menus', MenuController::class);

    // datamaster
    Route::resource('category', CategoryController::class);

    Route::get('transaction', [TransactionController::class, 'index'])->name('transaction.index');
    Route::get('transaction/{id}', [TransactionController::class, 'show'])->name('transaction.show');
    Route::post('transaction/{id}', [TransactionController::class, 'store'])->name('transaction.store');




    //profile
    Route::get('profile', [ProfileController::class , 'index'])->name('profile.index');

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\Auth;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Support\Str;
use App\Traits\Uuids;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, softDeletes, Uuids, HasRoles;
    protected $fillable = [
        'name',
        'email',
        'password',
        'type',
        'balance',
        'created_by',
        'updated_by',
        'deleted_by',
    ];

    protected $hidden = [
        // 'password',
        'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            if (empty($model->{$model->getKeyName()}))
                $model->{$model->getKeyName()} = Str::uuid()->toString();
            if (Schema::hasColumn($model->getTable(), 'created_by'))
                $model->created_by = Auth::id() ?? 'guest';
        });

        static::updating(function ($model) {
            if (Schema::hasColumn($model->getTable(), 'updated_by'))
                $model->updated_by = Auth::id() ?? 'guest';
        });

        static::deleting(function ($model) {
            if (Schema::hasColumn($model->getTable(), 'deleted_by')) {
                $model->deleted_by = Auth::id() ?? 'guest';
                $model->save();
            }
        });
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\UserDataTable;
use App\Http\Controllers\Controller;
use App\Http\Requests\UserRequest;
use App\Models\Role;
use App\Models\User;
use App\Models\BusinessInformation;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use View;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    protected $model;
    protected $view;

    public function __construct(User $user)
    {
        $this->middleware('can:user.list')->only('index');
        $this->middleware('can:user.create')->only('store');
        $this->middleware('can:user.update')->only('update');
        $this->middleware('can:user.delete')->only('destroy');

        $this->model    = $user;
        $this->view     = "pages.user";
        $this->route    = "users";
        $this->title    = "User";
        $this->roles    = Role::all();

        View::share('route', $this->route);
        View::share('view', $this->view);
        View::share('model', $this->model);
        View::share('title', $this->title);
        View::share('roles', $this->roles);
    }

    public function index(UserDataTable $dataTable)
    {
        return $dataTable->render($this->view . '.index');
    }

    public function store(UserRequest $request)
    {
        try {
            DB::beginTransaction();
            $payload = $request->all();
            $payload['password'] = Hash::make($payload['password']);
            $payload['type'] = $payload['role'];
            $payload['type'] = 'user';

            if($request->file('image')) {
                $filename = $request->file('image')->getClientOriginalName();
                Storage::putFileAs(
                    'public/images/user',
                    $request->file('image'),
                    $filename
                );
                $payload['image'] = $filename;
            }

            $data = $this->model->create($payload);
            $data->assignRole($payload['role']);

            $response = [
                'success' => true,
                'message' => 'Success save data',
                'data' => $data
            ];
            DB::commit();
            return response()->json($response);
        } catch (\Exception $e) {
            DB::rollback();
            $response = [
                'success' => false,
                'message' => 'Server Error',
                'data' => $e->getMessage()
            ];
            return response()->json($response, 500);
        }
    }


    public function show($id)
    {
        try {
            $data = $this->model->find($id);

            $response = [
                'success' => true,
                'message' => 'Success retrieve data',
                'data' => $data
            ];

            return response()->json($response);
        } catch (\Exception $e) {
            $response = [
                'success' => false,
                'message' => 'Server Error',
                'data' => $e->getMessage()
            ];
            return response()->json($response, 500);
        }
    }

    public function update(Request $request, $id)
    {
        try {
            DB::beginTransaction();
            $payload = $request->all();
            $user = $this->model->find($id);

            if (!empty($payload['password'])) $payload['password'] = Hash::make($payload['password']);
            else unset($payload['password']);
            $payload['type'] = $payload['role'];

            if($request->file('image')) {
                $filename = $request->file('image')->getClientOriginalName();
                Storage::putFileAs(
                    'public/images/user',
                    $request->file('image'),
                    $filename
                );
                $payload['image'] = $filename;
            }

            $data = $user->update($payload);
            DB::table('model_has_roles')->where('model_id',$user->id)->delete();
            $user->assignRole($payload['role']);

            $response = [
                'success' => true,
                'message' => 'Success save data',
                'data' => $data
            ];
            DB::commit();
            return response()->json($response);
        } catch (\Exception $e) {
            DB::rollback();
            $response = [
                'success' => false,
                'message' => $e->getMessage(),
                'data' => []
            ];
            return response()->json($response, 500);
        }
    }

    public function destroy($id)
    {
        try {
            $user = $this->model->find($id);
            $data = $user->delete();

            $response = [
                'success' => true,
                'message' => 'Success delete data',
                'data' => $data
            ];

            return response()->json($response);
        } catch (\Exception $e) {
            $response = [
                'success' => false,
                'message' => $e->getMessage(),
                'data' => []
            ];
            return response()->json($response, 500);
        }
    }
}

resources/views/pages/user/action.blade.php
<div class="dropdown">
    <button class="btn btn-sm btn-primary dropdown-toggle" type="button" id="dropdownMenuAction" data-bs-toggle="dropdown"
        aria-expanded="false">
        Action
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuAction">
        <li><a class="dropdown-item" href="{{ route('transaction.show', $id) }}">Show</a></li>
        <li><a class="dropdown-item edit-btn" href="#" data-id="{{ $id }}">Edit</a></li>
        <li>
            <hr class="dropdown-divider">
        </li>
        <li><a class="dropdown-item delete-btn" data-id="{{ $id }}" href="#">Delete</a></li>
    </ul>
</div>

resources/views/pages/user/form.blade.php
<!--begin::Modal-->
<div class="modal fade" tabindex="-1" id="user-modal" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-scrollable">
        <form method="post" action="" class="form needs-validation" id="user-form"
            enctype="multipart/form-data" autocomplete="off" novalidate>
            @csrf
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Form Users</h5>

                    <!--begin::Close-->
                    <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" data-bs-dismiss="modal"
                        aria-label="Close">
                        <span class="svg-icon svg-icon-2x"></span>
                    </div>
                    <!--end::Close-->
                </div>

                <div class="modal-body">

                    <div class="mb-10 fv-row">
                        <label for="role" class="form-label">Role</label>
                        <select name="role" id="role" class="form-control form-control-solid form-select mb-2">
                            <option value="" disabled selected>--Choose option--</option>
                            @foreach ($roles as $role)
                            <option value="{{ $role->name }}">{{ $role->name }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="mb-10 fv-row">
                        <label for="name" class="required form-label">Name</label>
                        <input type="text" class="form-control form-control-solid" name="name" placeholder="Name"
                            required />
                    </div>

                    <div class="mb-10 fv-row">
                        <label for="email" class="required form-label">Email</label>
                        <input type="email" class="form-control form-control-solid" name="email" placeholder="email"
                            required />
                    </div>

                    <div class="mb-10 fv-row">
                        <label for="password" class="form-label">Password</label>
                        <input type="password" class="form-control form-control-solid" name="password"
                            placeholder="Password" autocomplete="new-password" />
                    </div>

                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
                    <button class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </form>
    </div>
</div>
<!--end::Modal-->

resources/views/pages/user/index.blade.php
@extends('layouts.app')

@section('pageTitle', $title)

@section('metaTitle', $title)
@section('metaDescription', 'Tiga Digit Indonesia')

@section('breadcrumb')
    <x-global-component.breadcrumb :links="[
        [
            'url' => '#',
            'title' => 'User',
        ],
    ]" />
@endsection

@section('actionPage')
    <button type="button" class="btn btn-primary btn-hover-scale" data-bs-toggle="modal" data-bs-target="#user-modal">
        Create
    </button>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card card-sm">
                <div class="card-body pt-0 pb-0">
                    <div class="table-responsive">
                        {{ $dataTable->table() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    @include($view . '.form')
@endsection

@push('scripts')
    {{ $dataTable->scripts() }}
    @include($view . '.script')
@endpush

resources/views/pages/user/script.blade.php
<script>
    $(document).ready(function() {
        let method = 'POST'

        $(document).on('click', '.image-modal', function() {
            var index = $(".image-modal").index(this);
            $('.modal-show-image').attr('src', $(".image-modal").eq(index).attr('src'));
            $('.modal-image-preview').modal('show');
        });

        //STORE
        $('#user-form').submit(function(e) {
            e.preventDefault()
            const payload = new FormData(this)
            const url = $(this).attr('action')
            const validator = document.getElementById('user-form').checkValidity()
            if (!validator) {
                clearValidator()
                formValidator()
            }
            else {
                $.ajax({
                    url: url,
                    headers: {
                        'X-CSRF-TOKEN': '{{ csrf_token() }}'
                    },
                    // method: method, //UNTUK DINAMIS METHOD
                    method: 'POST', //HARDCODE KE POST KARENA FormData (upload gambar)
                    data: payload,
                    processData: false,
                    contentType: false,
                })
                .done(response => {
                    if (response.success) {
                        Swal.fire({
                            icon: 'success',
                            title: 'Success',
                            text: response.message
                        })
    
                        $('.dataTable').DataTable().ajax.reload()
                        $('#user-modal').modal('hide')
                    }
                    clearValidator()
                })
                .fail(response => {
                    Swal.fire({
                        icon: 'error',
                        title: 'Error',
                        text: response.responseJSON.message
                    })
                })
            }
        })
        // validator
        function formValidator() {
            let valid = true
            $('input[required], select[required]').each(function() {
                if (!this.checkValidity()) {
                    valid = false
                    $(this).addClass('is-invalid')
                    $(this).after('<div class="invalid-feedback">' + this.validationMessage + '</div>')
                }
            })
            return valid;
        }
        function clearValidator(){
            $('.invalid-feedback').remove()
            $('input[required], select[required]').removeClass('is-invalid')
        }

        //DELETE
        $(document).on('click', '.delete-btn', function() {
            Swal.fire({
                title: 'Are you sure',
                icon: 'info',
                showDenyButton: true,
                confirmButtonText: 'Yes',
                denyButtonText: `No`,
            }).then((result) => {
                if (result.isConfirmed) {
                    const url = '{{ url('user') }}/' + $(this).data('id')
                    $.ajax({
                        url: url,
                        method: 'DELETE',
                        headers: {
                            'X-CSRF-TOKEN': '{{ csrf_token() }}'
                        }
                    }).done(response => {
                        console.log(response)
                        Swal.fire({
                            icon: 'success',
                            title: 'Success',
                            message: response.message
                        })
                        $('.dataTable').DataTable().ajax.reload()
                    })
                }
            })
        })

        //EDIT
        $(document).on('click', '.edit-btn', function() {
            const url = '{{ url('user') }}/' + $(this).data('id')
            $('#user-form').attr('action', url)
            method = 'PUT'

            let data = {}
            $.get(url).done(response => {
                if (response.success) data = response.data
                setForm(data)
                $('#user-modal').modal('show')
            })
        })

        function setForm(data) {
            $('#role').val(data.type).change()
            $('input[name=name]').val(data.name)
            $('input[name=email]').val(data.email)
            $('input[name=username]').val(data.username)
            $('input[name=phone_number]').val(data.phone_number)
            $('select[name=role]').val(data.type).change()
            $('#address').val(data.address)
            $('.image-input-empty').attr('style', 'background-image: url({{ asset('storage/images/user') }}/' +
                encodeURIComponent(data.image) + ')')
        }

        function clearForm() {
            $('#role').val('').change()
            $('input[name=name]').val('')
            $('input[name=email]').val('')
            $('input[name=username]').val('')
            $('input[name=phone_number]').val('')
            $('select[name=role]').val('').change()
            $('#address').val('')
        }

        $('.modal').on('hidden.bs.modal', function(event) {
            $('#user-form').attr('action', '{{ route('user.store') }}')
            //hapus gambar ketika modal ditutup
            clearForm()
            clearValidator()
            $('.btn-cancel-img').click()
            method = 'POST'
            $('.image-input-empty').css('background-image',
                'url("{{ asset('assets/media/avatars/blank.png') }}")')
        })

    })
</script>