routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;

// user management
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\PermissionController;

// authentication
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\ForgotPasswordController;
use App\Http\Controllers\ProfileController;

// data env
use App\Http\Controllers\MenuController;

// data master
use App\Http\Controllers\AdjustmentTypeController;
use App\Http\Controllers\BusinessInformationController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\CashAndBankController;
use App\Http\Controllers\CashAndBankSubcategoryController;
use App\Http\Controllers\ChartOfAccountController;
use App\Http\Controllers\CommodityCategoryController;
use App\Http\Controllers\CurrencyController;
use App\Http\Controllers\CostTypeOtherController;
use App\Http\Controllers\SpecialNotificationBarController;
use App\Http\Controllers\FormStyleController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\InventoryTypeController;
use App\Http\Controllers\ProductCategoryController;
use App\Http\Controllers\ProductionCostsTypeController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\DiscountTypeController;
use App\Http\Controllers\TaxTypesController;
use App\Http\Controllers\AssetCategoryController;
use App\Http\Controllers\BannersTutorialController;
use App\Http\Controllers\PromotionalBannersController;
use App\Http\Controllers\TaxesController;
use App\Http\Controllers\SolutionListController;
use App\Http\Controllers\AssetsController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\UnitsController;
use App\Http\Controllers\SampleTransactionController;
use App\Http\Controllers\CompanyCustomerController;
use App\Http\Controllers\ShopController;


use App\Http\Controllers\CommoditySecurityController;
use App\Http\Controllers\CompanyCategoryController;
use App\Http\Controllers\CompanyRoleController;
use App\Http\Controllers\MarketingChannelController;
use App\Http\Controllers\NumberOfEmployeeController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\TransactionTagController;



// transaction
use App\Http\Controllers\TransactionController;
use App\Http\Requests\SolutionListRequest;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
// Authentications
Route::get('/login', [AuthController::class, 'loginForm'])->name('login');
Route::post('/login-submit', [AuthController::class, 'login'])->name('login.submit');
Route::get('/register', [AuthController::class, 'registerForm'])->name('register-form');
Route::post('/register/verify-email', [AuthController::class, 'registerVerifyEmail'])->name('register.verify-email');
Route::post('/register/get-otp', [AuthController::class, 'registerGetOtp'])->name('register.get-otp');
Route::post('/register/verify-otp', [AuthController::class, 'registerVerifyOtp'])->name('register.verify-otp');
Route::post('/register/user', [AuthController::class, 'registerUser'])->name('register.user');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout.user');

// forgot password
Route::get('forget-password', [ForgotPasswordController::class, 'showForgetPasswordForm'])->name('forget.password.get');
Route::post('forget-password', [ForgotPasswordController::class, 'submitForgetPasswordForm'])->name('forget.password.post');
Route::get('reset-password-status/{status}', [ForgotPasswordController::class, 'resetPasswordStatus'])->name('reset.password.status');
Route::get('reset-password/{token}', [ForgotPasswordController::class, 'showResetPasswordForm'])->name('reset.password.get');
Route::post('reset-password/{token}', [ForgotPasswordController::class, 'submitResetPasswordForm'])->name('reset.password.post');

Route::middleware(['auth'])->group(function () {
    Route::get('/register/complete', [AuthController::class, 'registerComplete'])->name('register.complete');
    Route::post('/register', [AuthController::class, 'register'])->name('register');

    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('user', UserController::class)->except(['update']);
    Route::post('user/{id}', [UserController::class, 'update'])->name('user.update');
    Route::post('roles/{role}', [RoleController::class, 'update'])->name('admin.roles.update');
    Route::resource('roles', RoleController::class);
    Route::resource('permissions', PermissionController::class);

    // data env
    Route::resource('menus', MenuController::class);

    // datamaster
    Route::resource('category', CategoryController::class);

    Route::get('transaction', [TransactionController::class, 'index'])->name('transaction.index');
    Route::get('transaction/{id}', [TransactionController::class, 'show'])->name('transaction.show');
    Route::post('transaction/{id}', [TransactionController::class, 'store'])->name('transaction.store');




    //profile
    Route::get('profile', [ProfileController::class , 'index'])->name('profile.index');

});

app/Models/Permission.php
<?php

namespace App\Models;

use App\Traits\Uuids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Permission extends \Spatie\Permission\Models\Permission
{
    use Uuids, SoftDeletes;
    protected $keyType = 'string';
    protected $primaryKey = 'id';
    public $incrementing = false;

    protected $fillable = [
        'name',
        'guard_name',
    ];

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

    public static $rules = [
        'name'             => 'required|unique:groups,name',
        'description'      => 'required',
        // 'parent_id'        => 'required_if:category,==,1'
    ];
}

app/Http/Controllers/PermissionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\DataTables\PermissionDataTable;
use App\Http\Requests\PermissionRequest;
use App\Models\Permission;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use View;

class PermissionController extends Controller
{
    protected $model;
    protected $view;

    public function __construct(Permission $model)
    {
        $this->middleware('can:permission.list')->only('index');
        $this->middleware('can:permission.create')->only('store');
        $this->middleware('can:permission.update')->only('update');
        $this->middleware('can:permission.delete')->only('destroy');

        $this->model    = $model;
        $this->view     = "pages.permission";
        $this->route    = "permissions";
        $this->title    = "Permission";

        View::share('route', $this->route);
        View::share('view', $this->view);
        View::share('model', $this->model);
        View::share('title', $this->title);
    }
    
    
    public function index(PermissionDataTable $dataTable)
    {
        return $dataTable->render($this->view . '.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // $roles = Role::all();
        // return  to_route('', ['roles' => $roles]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PermissionRequest $request)
    {
        try {
            $input = $request->all();
            if($request->has('crud')) {
                foreach(config('constants.role_permissions.form_generator_values') as $value) {
                    $name = $input['name'].'.'.$value;
                    $payload = [...$input, 'name' => $name];
                    $data[] = $this->model->create($payload);
                }
            } else {
                $data = $this->model->create($input);
            }

            $response = [
                'success' => true,
                'message' => 'Success save data',
                'data' => $data
            ];

            return response()->json($response);
        } catch (\Exception $e) {
            $response = [
                'success' => false,
                'message' => 'Server Error',
                'data' => $e->getMessage()
            ];
            return response()->json($response, 500);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try {
            $data = $this->model->find($id);

            $response = [
                'success' => true,
                'message' => 'Success retrieve data',
                'data' => $data
            ];

            return response()->json($response);
        } catch (\Exception $e) {
            $response = [
                'success' => false,
                'message' => 'Server Error',
                'data' => $e->getMessage()
            ];
            return response()->json($response, 500);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $roles)
    {
        //
    }


    public function update(PermissionRequest $request, $id)
    {
        try {
            $input = $request->all();
            $data = $this->model->find($id);

            $data = $data->update($input);

            $response = [
                'success' => true,
                'message' => 'Success save data',
                'data' => $data
            ];

            return response()->json($response);
        } catch (\Exception $e) {
            $response = [
                'success' => false,
                'message' => $e->getMessage(),
                'data' => []
            ];
            return response()->json($response, 500);
        }
    }

    public function destroy($id)
    {
        try {
            $data = $this->model->find($id);
            $data = $data->delete();

            $response = [
                'success' => true,
                'message' => 'Success delete data',
                'data' => $data
            ];

            return response()->json($response);
        } catch (\Exception $e) {
            $response = [
                'success' => false,
                'message' => $e->getMessage(),
                'data' => []
            ];
            return response()->json($response, 500);
        }
    }
}

resources/views/pages/permission/action.blade.php
<div class="dropdown">
    <button class="btn btn-sm btn-primary dropdown-toggle" type="button" id="dropdownMenuAction" data-bs-toggle="dropdown"
        aria-expanded="false">
        Action
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuAction">
        <li><a class="dropdown-item" href="#">Show</a></li>
        <li><a class="dropdown-item edit-btn" href="#" data-id="{{ $id }}">Edit</a></li>
        <li>
            <hr class="dropdown-divider">
        </li>
        <li><a class="dropdown-item delete-btn" data-id="{{ $id }}" href="#">Delete</a></li>
    </ul>
</div>

resources/views/pages/permission/form.blade.php
<!--begin::Modal-->
<div class="modal fade" tabindex="-1" id="permission-modal" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-scrollable">
        <form method="post" action="{{ route($route . '.store') }}" class="form needs-validation" id="permission-form"
            autocomplete="off" novalidate>
            @csrf
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Form {{ $title }}</h5>

                    <!--begin::Close-->
                    <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" data-bs-dismiss="modal"
                        aria-label="Close">
                        <span class="svg-icon svg-icon-2x"></span>
                    </div>
                    <!--end::Close-->
                </div>

                <div class="modal-body">

                    <div class="fv-row mb-10">
                        <div class="mb-10 fv-row">
                            <label for="name" class="required form-label">Name</label>
                            <input type="text" class="form-control form-control-solid" name="name"
                                placeholder="Name" required />
                        </div>

                        <input type="hidden" value="web" class="form-control form-control-solid" name="guard_name"
                            placeholder="Guard Name" required />

                        <div class="mb-10 fv-row" id="generate-crud">
                            <div class="input-group mb-3">
                                <div class="input-group-text">
                                    <input class="form-check-input mt-0" type="checkbox" name="crud"
                                        aria-label="Checkbox for crud">
                                </div>
                                <input type="text" disabled class="form-control"
                                    placeholder="Generate Create, Read, Update, Delete permissions ?"
                                    aria-label="Text input with checkbox">
                            </div>
                        </div>


                        <div class="modal-footer">
                            <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
                            <button class="btn btn-primary">Save changes</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<!--end::Modal-->

resources/views/pages/permission/index.blade.php
@extends('layouts.app')

@section('pageTitle', $title)

@section('metaTitle', $title)
@section('metaDescription', 'Tiga Digit Indonesia')

@section('breadcrumb')
    <x-global-component.breadcrumb :links="[
        [
            'url' => '#',
            'title' => 'Permission',
        ],
    ]" />
@endsection

@section('actionPage')
    <button type="button" class="btn btn-primary btn-hover-scale" data-bs-toggle="modal" data-bs-target="#permission-modal">
        Create
    </button>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card card-sm">
                <div class="card-body pt-0 pb-0">
                    <div class="table-responsive">
                        {{ $dataTable->table() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    @include($view . '.form')   
@endsection

@push('scripts')
    {{ $dataTable->scripts() }}
    @include($view . '.script')
@endpush

resources/views/pages/permission/script.blade.php
<script>
    $(document).ready(function() {
        let method = 'POST'

        //STORE
        $('#permission-form').submit(function(e) {
            e.preventDefault()
            const payload = $(this).serialize()
            const url = $(this).attr('action')
            const validator = document.getElementById('permission-form').checkValidity()

            if (validator) {
                $.ajax({
                        url: url,
                        method: method,
                        data: payload
                    })
                    .done(response => {
                        if (response.success) {
                            Swal.fire({
                                icon: 'success',
                                title: 'Success',
                                text: response.message
                            })

                            $('.dataTable').DataTable().ajax.reload()
                            $('#permission-modal').modal('hide')
                        }
                    })
                    .fail(response => {
                        Swal.fire({
                            icon: 'error',
                            title: 'Error',
                            text: response.responseJSON.message
                        })
                    })
            }

        })


        //DELETE
        $(document).on('click', '.delete-btn', function() {
            Swal.fire({
                title: 'Are you sure',
                icon: 'info',
                showDenyButton: true,
                confirmButtonText: 'Yes',
                denyButtonText: `No`,
            }).then((result) => {
                /* Read more about isConfirmed, isDenied below */
                if (result.isConfirmed) {
                    const url = '{{ url('permissions') }}/' + $(this).data('id')
                    $.ajax({
                        url: url,
                        method: 'DELETE',
                        headers: {
                            'X-CSRF-TOKEN': '{{ csrf_token() }}'
                        }
                    }).done(response => {
                        console.log(response)
                        Swal.fire({
                            icon: 'success',
                            title: 'Success',
                            message: response.message
                        })
                        $('.dataTable').DataTable().ajax.reload()
                    })
                }
            })
        })

        //EDIT
        $(document).on('click', '.edit-btn', function() {
            const url = '{{ url('permissions') }}/' + $(this).data('id')
            $('#permission-form').attr('action', url)
            method = 'PUT'

            let data = {}
            $.get(url).done(response => {
                if (response.success) data = response.data
                setForm(data)
                $('#generate-crud').hide()
                $('#permission-modal').modal('show')
            })
        })

        function setForm(data) {
            $('input[name=name]').val(data.name)
            $('input[name=guard_name]').val(data.guard_name)
        }

        function clearForm() {
            $('input[name=name]').val()
            $('input[name=guard_name]').val()
        }

        $('.modal').on('hidden.bs.modal', function(event) {
            $('#permission-form').attr('action', '{{ route('permissions.store') }}')
            method = 'POST'
            clearForm()
            $('#generate-crud').show()
        })

    })
</script>