routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;

// user management
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\PermissionController;

// authentication
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\ForgotPasswordController;
use App\Http\Controllers\ProfileController;

// data env
use App\Http\Controllers\MenuController;

// data master
use App\Http\Controllers\AdjustmentTypeController;
use App\Http\Controllers\BusinessInformationController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\CashAndBankController;
use App\Http\Controllers\CashAndBankSubcategoryController;
use App\Http\Controllers\ChartOfAccountController;
use App\Http\Controllers\CommodityCategoryController;
use App\Http\Controllers\CurrencyController;
use App\Http\Controllers\CostTypeOtherController;
use App\Http\Controllers\SpecialNotificationBarController;
use App\Http\Controllers\FormStyleController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\InventoryTypeController;
use App\Http\Controllers\ProductCategoryController;
use App\Http\Controllers\ProductionCostsTypeController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\DiscountTypeController;
use App\Http\Controllers\TaxTypesController;
use App\Http\Controllers\AssetCategoryController;
use App\Http\Controllers\BannersTutorialController;
use App\Http\Controllers\PromotionalBannersController;
use App\Http\Controllers\TaxesController;
use App\Http\Controllers\SolutionListController;
use App\Http\Controllers\AssetsController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\UnitsController;
use App\Http\Controllers\SampleTransactionController;
use App\Http\Controllers\CompanyCustomerController;
use App\Http\Controllers\ShopController;


use App\Http\Controllers\CommoditySecurityController;
use App\Http\Controllers\CompanyCategoryController;
use App\Http\Controllers\CompanyRoleController;
use App\Http\Controllers\MarketingChannelController;
use App\Http\Controllers\NumberOfEmployeeController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\TransactionTagController;



// transaction
use App\Http\Controllers\TransactionController;
use App\Http\Requests\SolutionListRequest;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
// Authentications
Route::get('/login', [AuthController::class, 'loginForm'])->name('login');
Route::post('/login-submit', [AuthController::class, 'login'])->name('login.submit');
Route::get('/register', [AuthController::class, 'registerForm'])->name('register-form');
Route::post('/register/verify-email', [AuthController::class, 'registerVerifyEmail'])->name('register.verify-email');
Route::post('/register/get-otp', [AuthController::class, 'registerGetOtp'])->name('register.get-otp');
Route::post('/register/verify-otp', [AuthController::class, 'registerVerifyOtp'])->name('register.verify-otp');
Route::post('/register/user', [AuthController::class, 'registerUser'])->name('register.user');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout.user');

// forgot password
Route::get('forget-password', [ForgotPasswordController::class, 'showForgetPasswordForm'])->name('forget.password.get');
Route::post('forget-password', [ForgotPasswordController::class, 'submitForgetPasswordForm'])->name('forget.password.post');
Route::get('reset-password-status/{status}', [ForgotPasswordController::class, 'resetPasswordStatus'])->name('reset.password.status');
Route::get('reset-password/{token}', [ForgotPasswordController::class, 'showResetPasswordForm'])->name('reset.password.get');
Route::post('reset-password/{token}', [ForgotPasswordController::class, 'submitResetPasswordForm'])->name('reset.password.post');

Route::middleware(['auth'])->group(function () {
    Route::get('/register/complete', [AuthController::class, 'registerComplete'])->name('register.complete');
    Route::post('/register', [AuthController::class, 'register'])->name('register');

    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('user', UserController::class)->except(['update']);
    Route::post('user/{id}', [UserController::class, 'update'])->name('user.update');
    Route::post('roles/{role}', [RoleController::class, 'update'])->name('admin.roles.update');
    Route::resource('roles', RoleController::class);
    Route::resource('permissions', PermissionController::class);

    // data env
    Route::resource('menus', MenuController::class);

    // datamaster
    Route::resource('category', CategoryController::class);

    Route::get('transaction', [TransactionController::class, 'index'])->name('transaction.index');
    Route::get('transaction/{id}', [TransactionController::class, 'show'])->name('transaction.show');
    Route::post('transaction/{id}', [TransactionController::class, 'store'])->name('transaction.store');




    //profile
    Route::get('profile', [ProfileController::class , 'index'])->name('profile.index');

});

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\TransactionDataTable;
use App\Http\Requests\Transaction;
use App\Models\Category;
use App\Models\Transaction as ModelsTransaction;
use App\Models\User;
use Illuminate\Http\Request;
use View;

class TransactionController extends Controller
{

    protected $model;
    protected $view;

    public function __construct(User $user)
    {
        $this->middleware('can:transaction.list')->only('index');
        $this->middleware('can:transaction.create')->only('store');
        $this->middleware('can:transaction.update')->only('update');
        $this->middleware('can:transaction.delete')->only('destroy');

        $this->model    = $user;
        $this->view     = "pages.transaction";
        $this->route    = "transaction";
        $this->title    = "Transaction";
        $this->categories    = Category::all();

        View::share('route', $this->route);
        View::share('view', $this->view);
        View::share('model', $this->model);
        View::share('title', $this->title);
        View::share('categories', $this->categories);
    }

    public function index(TransactionDataTable $dataTable)
    {
        return $dataTable->render($this->view . '.index');
    }

    public function show($id)
    {
        $data = User::where('id',$id)->first();
        $transactions = ModelsTransaction::where('user_id', $id)->get();
        return view('pages.transaction.create',compact('data','transactions'));
    }

    public function store(Request $request, $id)
    {
        $input = $request->validate([
            'category_id' => 'required',
            'balance' => 'required',
        ]);

        $user = User::find($id);
        
        $category = Category::where('id',$request->category_id)->first();

        if ($category->status == 1) {
            $inputNewBalance = $input['balance'];
            $modelNewBalance = $user->balance;
            
            $sumNewBalance = $inputNewBalance + $modelNewBalance;
        } else {
            $inputNewBalance = $input['balance'];
            $modelNewBalance = $user->balance;
            
            $sumNewBalance = $modelNewBalance - $inputNewBalance;
        }
        
        $transaction = new ModelsTransaction([
            'user_id' => $id,
            'category_id' => $input['category_id'],
            'change_balance' => $input['balance'],
            'out_change' => $input['balance'],
            'out_balance' => $user->balance
        ]);
        
        
        $transaction->new_balance = $sumNewBalance;
        $transaction->save();
    

        $user->update(['balance' => $sumNewBalance]);

        return back();
    }
}

resources/views/pages/transaction/create.blade.php
@extends('layouts.app')

@section('pageTitle', $title)

@section('metaTitle', $title)
@section('metaDescription', 'Tiga Digit Indonesia')

@section('breadcrumb')
    <x-global-component.breadcrumb :links="[
        [
            'url' => '#',
            'title' => 'User',
        ],
    ]" />
@endsection

@section('content')

    <div class="row">
        <div class="col-12 mb-4">
            <div class="card card sm">
                <div class="card-body">
                    <table class="table table-responsive">
                        <thead>
                            <tr>
                                <th>User</th>
                                <th>Balance</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{{ $data->name }}</td>
                                <td>{{ $data->balance }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-4 mb-4">
        <div class="col-12">
            <div class="card card-sm">
                <div class="card-body pt-0 pb-0">
                    <form action="{{ route('transaction.store', $data->id) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="mb-10 fv-row">
                            <label for="category_id" class="form-label">Category</label>
                            <select name="category_id" id="category_id"
                                class="form-control form-control-solid form-select mb-2">
                                <option value="" disabled selected>--Choose option--</option>
                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="mb-10 fv-row">
                            <label for="balance" class="required form-label">Balance</label>
                            <input type="number" class="form-control form-control-solid" name="balance"
                                placeholder="Balance" />
                        </div>
                        <button type="submit" class="btn btn-primary btn-hover-scale">
                            Create
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12 mb-4">
            <div class="card card sm">
                <div class="card-body">
                    <table class="table table-responsive">
                        <thead>
                            <tr>
                                <th>User</th>
                                <th>Category</th>
                                <th>New Balance</th>
                                <th>Out Balance</th>
                                <th>Change Balance</th>
                            </tr>
                        </thead>
                        <tbody>
                          @foreach ($transactions as $item)
                            <tr>
                                    <td>{{ $item->user->name }}</td>
                                    <td>{{ $item->category->name }}</td>
                                    <td>{{ $item->new_balance }}</td>
                                    <td>{{ $item->out_balance }}</td>
                                    <td>{{ $item->change_balance }}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>



@endsection

@push('scripts')
@endpush

resources/views/pages/transaction/index.blade.php
@extends('layouts.app')

@section('pageTitle', $title)

@section('metaTitle', $title)
@section('metaDescription', 'Tiga Digit Indonesia')

@section('breadcrumb')
    <x-global-component.breadcrumb :links="[
        [
            'url' => '#',
            'title' => 'Transaction',
        ],
    ]" />
@endsection

@section('content')

    <div class="row">
        <form action="{{ route('transaction.index') }}" method="GET" class="row g-3">
            @csrf
            <div class="col-md-4">
                <div class="mb-10 fv-row">
                    <label for="start_date" class="required form-label">Start Date</label>
                    <input type="date" class="form-control form-control-solid" name="start_date" placeholder=""
                        value="{{ request('start_date') }}" required />
                </div>
            </div>
            <div class="col-md-4">
                <div class="mb-10 fv-row">
                    <label for="end_date" class="required form-label">End Date</label>
                    <input type="date" class="form-control form-control-solid" name="end_date" placeholder=""
                        value="{{ request('end_date') }}" required />
                </div>
            </div>
            <div class="col-md-2">
                <div class="mt-7 fv-row">
                    <button type="submit" class="btn btn-primary">Search</button>
                </div>
            </div>
        </form>
    </div>


    <div class="row">
        <div class="col-12">
            <div class="card card-sm">
                <div class="card-body pt-0 pb-0">
                    <div class="table-responsive">
                        {{ $dataTable->table() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    {{ $dataTable->scripts() }}
    @include($view . '.script')
@endpush

resources/views/pages/transaction/script.blade.php
<script>
    $(document).ready(function() {
        let method = 'POST'

        //STORE
        $('#role-form').submit(function(e) {
            e.preventDefault()
            const payload = $(this).serialize()
            const url = $(this).attr('action')
            const validator = document.getElementById('role-form').checkValidity()

            if (validator) {
                $.ajax({
                        url: url,
                        method: method,
                        data: payload
                    })
                    .done(response => {
                        if (response.success) {
                            Swal.fire({
                                icon: 'success',
                                title: 'Success',
                                text: response.message
                            })
                            
                            $('.dataTable').DataTable().ajax.reload()
                            $('#role-modal').modal('hide')
                        }
                    })
                    .fail(response => {
                        Swal.fire({
                            icon: 'error',
                            title: 'Error',
                            text: response.responseJSON.message
                        })
                    })
            }

        })


        //DELETE
        $(document).on('click', '.delete-btn', function() {
            Swal.fire({
                title: 'Are you sure',
                icon: 'info',
                showDenyButton: true,
                confirmButtonText: 'Yes',
                denyButtonText: `No`,
            }).then((result) => {
                /* Read more about isConfirmed, isDenied below */
                if (result.isConfirmed) {
                    const url = '{{ url('roles') }}/' + $(this).data('id')
                    $.ajax({
                        url: url,
                        method: 'DELETE',
                        headers: {
                            'X-CSRF-TOKEN': '{{ csrf_token() }}'
                        }
                    }).done(response => {
                        console.log(response)
                        Swal.fire({
                            icon: 'success',
                            title: 'Success',
                            message: response.message
                        })
                        $('.dataTable').DataTable().ajax.reload()
                    })
                }
            })
        })

        //EDIT
        $(document).on('click', '.edit-btn', function() {
            const url = '{{ url('roles') }}/' + $(this).data('id')
            $('#role-form').attr('action', url)
            method = 'PUT'

            let data = {}
            $.get(url).done(response => {
                if (response.success) data = response.data
                setForm(data)
                console.log(data)
                $('#role-modal').modal('show')
            })
        })

        function setForm(data) {
            $('input[name=name]').val(data.name)
            $('input[name=guard_name][value='+data.guard_name+']').prop("checked",true)
            
            $.each(data.permission, function(index) {
                $('[id='+index+']').prop("checked",true)
            });
        }
        function clearForm() {
            $('input[name=name]').val()
            $('input[name=guard_name]').prop("checked",false) 
            $('.box-permission').prop("checked",false)
        }

        $('.modal').on('hidden.bs.modal', function(event) {
            $('#role-form').attr('action', '{{ route('roles.store') }}')
            method = 'POST'
            clearForm()
        })
        
        $("#selectAll").click(function () {
            var selectAllChecked = $(this).prop("checked");
            $(".box-permission").prop("checked", selectAllChecked);
        });

        // Memeriksa apakah semua kotak centang dicentang, jika ya, centang tombol "Select All"
        $(".box-permission").click(function () {
            var allChecked = $(".box-permission:checked").length === $(".box-permission").length;
            $("#selectAll").prop("checked", allChecked);
        });

    })
</script>